[Scene]
schema = 1
id = "dark_scene"
title = "Dark Scene"
data_file = "game_over.dat.conf"

[Scene.Lighting]
file = "dark_scene.lighting.conf"
schema = "DarkVoid"
blend_in_seconds = 0.45

[Scene.Environment]
clear_color = [0, 0, 0, 255]
ambient_light = [0.03, 0.03, 0.05]

[Scene.Load]
actors = [
	"game_over_background",
	"game_over_controller",
	"game_over_fader",
]

[Scene.UI]
documents = [
	"game_over.ui.conf",
]

[Scene.Persistence]
unload_scene_lifetime_actors_on_exit = true

[Scene.Transition]
next_scene = ""
transition_effect = "none"
