[Data]
schema = 1

[[Actors]]
id = "game_over_controller"
enabled = true
layer = 0
lifetime = "scene"
tags = ["ui", "controller"]

[Actors.Components.Script]
module = "scripts/game_over.lua"

[Actors.Components.Rigidbody]
body_type = "static"
simulated = false
use_gravity = false