[LightingGlobal]
schema = 1
active_profile = "default"
allow_missing_scene_lighting = false

[LightingGlobal.Paths]
lighting_dir = "./lighting"

[LightingGlobal.Defaults]
file = "starting_scene.lighting.conf"
schema = "OutdoorDay"

[[LightingGlobal.SceneMap]]
scene_id = "starting_scene"
file = "starting_scene.lighting.conf"
default_schema = "OutdoorDay"

[[LightingGlobal.SceneMap]]
scene_id = "game_over"
file = "dark_scene.lighting.conf"
default_schema = "DarkMenu"

[[LightingGlobal.SceneMap]]
scene_id = "dark_scene"
file = "dark_scene.lighting.conf"
default_schema = "DarkVoid"
