[Data]
schema = 1

[PrefabRefs]
Player = "prefabs/player.prefab.conf"
Crate = "prefabs/crate.prefab.conf"

[[Actors]]
id = "main_camera"
enabled = true
lifetime = "scene" # scene | game
tags = ["camera"]

[Actors.Transform]
position = [0.0, 5.0, 12.0]
rotation_euler = [25.0, 180.0, 0.0]
scale = [1.0, 1.0, 1.0]

[Actors.Components.Camera]
projection = "perspective"
fov = 60.0
near_clip = 0.1
far_clip = 1000.0

[Actors.Components.Script]
module = "scripts/camera_follow.lua"

[[Actors]]
id = "sun_light"
enabled = true
lifetime = "scene"
tags = ["light"]

[Actors.Transform]
position = [12.0, 20.0, -8.0]
rotation_euler = [50.0, -35.0, 0.0]
scale = [1.0, 1.0, 1.0]

[Actors.Components.DirectionalLight]
color = [255, 245, 210]
intensity = 1.25

[[Actors]]
id = "player_spawn"
enabled = true
layer = 10
lifetime = "scene"
prefab = "Player"
tags = ["player"]

[Actors.Transform]
position = [0.0, 1.0, 0.0]
anchor = "center"

[Actors.Overrides.Components.Health]
current = 100
max = 100

[Actors.Overrides.Components.Script]
module = "scripts/player.lua"

[Actors.Overrides.Components.AnimatedSprite]
anim = "assets/anims/player.anim.conf"
position = [0.0, 0.0]
scale = 2.0

[[Actors]]
id = "ground_tile_001"
enabled = true
lifetime = "scene"
tags = ["environment", "ground"]

[Actors.Transform]
position = [0.0, 0.0, 0.0]
rotation_euler = [0.0, 0.0, 0.0]
scale = [20.0, 1.0, 20.0]

[Actors.Components.MeshRenderer]
mesh = "meshes/ground_tile.glb"
material = "materials/ground.mat"

[Actors.Components.Collider]
shape = "box"
is_trigger = false
friction = 0.8

[[Actors]]
id = "crate_001"
enabled = true
layer = 0
lifetime = "scene"
prefab = "Crate"
tags = ["prop", "interactable"]

[Actors.Transform]
position = [260.0, 0.5, -1.0]

[Actors.Overrides.Components.Health]
current = 30

[Actors.Overrides.Components.Script]
module = "scripts/crate.lua"

[Actors.Overrides.Components.StaticSprite]
texture = "assets/Sprites/crate.jpeg"
position = [0.0, 0.0]
scale = 1.0
