[Data]
schema = 1

[PrefabRefs]
Player = "prefabs/player.prefab.conf"
Crate = "prefabs/crate.prefab.conf"

[[Actors]]
id = "main_camera"
enabled = true
lifetime = "scene"
tags = ["camera"]

[Actors.Transform]
position = [0.0, 5.0, 12.0]
rotation_euler = [25.0, 180.0, 0.0]
scale = [1.0, 1.0, 1.0]

[Actors.Components.Camera]
projection = "perspective"
fov = 60.0
near_clip = 0.1
far_clip = 1000.0

[Actors.Components.Rigidbody]
body_type = "kinematic"
use_gravity = false
freeze_rotation = true

[Actors.Components.Script]
module = "scripts/camera_follow.lua"

[[Actors]]
id = "sun_light"
enabled = true
lifetime = "scene"
tags = ["light"]

[Actors.Transform]
position = [12.0, 20.0, -8.0]
rotation_euler = [50.0, -35.0, 0.0]
scale = [1.0, 1.0, 1.0]

[Actors.Components.DirectionalLight]
color = [255, 245, 210]
intensity = 1.25

[Actors.Components.Rigidbody]
body_type = "static"
simulated = false
use_gravity = false

[[Actors]]
id = "player_spawn"
enabled = true
layer = 10
lifetime = "scene"
prefab = "Player"
tags = ["player"]

[Actors.Transform]
position = [0.0, 1.0, 0.0]
anchor = "center"

[Actors.Overrides.Components.Health]
current = 100
max = 100

[Actors.Overrides.Components.Script]
modules = ["scripts/player.lua", "scripts/music_start.lua"]

[Actors.Overrides.Components.Collider]
# Collider debug export for actor 'player_spawn' (index 0)
offset = [9.0, 6.0]
size = [43.0, 58.0]
enabled = true
is_trigger = false

[Actors.Overrides.Components.Rigidbody]
body_type = "dynamic"
mass = 1.0
gravity_scale = 1.0
linear_drag = 2.0
angular_drag = 0.0
use_gravity = true
freeze_rotation = true

[Actors.Overrides.Components.AnimatedSprite]
anim = "assets/anims/player.anim.conf"
position = [0.0, 0.0]
scale = 2.0

[[Actors]]
id = "crate_spawner"
enabled = true
layer = 0
lifetime = "scene"
tags = ["spawner"]

[Actors.Components.Script]
module = "scripts/crate_create.lua"

[Actors.Components.Rigidbody]
body_type = "static"
simulated = false
use_gravity = false