[Animation]
default="Fly"
flip_x_from_actor_movement=false
flip_x_deadzone=0.01
flip_x_when_param_negative=true

[Sheets]
mage_sheet="assets/Sprites/mage.png"

[Fly]
sheet="mage_sheet"
fps=10.0
loop=true
frames=[
    [0, 0, 16, 16],
    [16, 0, 16, 16],
    [32, 0, 16, 16],
    [48, 0, 16, 16],
]