[Animation]
default=Idle

# Have timing & other settings up here

[Sheets]
idle_sheet="assets/Sprites/player/Pink_Monster/Pink_Monster_Idle_4.png"
walk_sheet="assets/Sprites/player/Pink_Monster/Pink_Monster_Walk_6.png"

[Idle]
sheet=idle_sheet
frames=... # This should be replaced with the actual frame data for the idle animation.
plug = {
    "walk": { ... } # This should be replaced with the actual transition data for the walk animation.
                    # Like for example what conditions trigger the transition to walk
                    # or how many frames to still display idle before transitioning to walk.
}

[Walk]
sheet=walk_sheet
frames=... # This should be replaced with the actual frame data for the walk animation.
plug = {
    "idle": { ... } # This should be replaced with the actual transition data for the idle animation.
                    # Like for example what conditions trigger the transition to idle
                    # or how many frames to still display walk before transitioning to idle.
}
