[Prefab]
schema = 1
id = "Crate"

[Prefab.Defaults]
enabled = true
lifetime = "scene"
layer = 20
tags = ["prop"]

[Prefab.Transform]
position = [0.0, 0.0, 0.0]
rotation_euler = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]
anchor = "center"

[Prefab.Components.MeshRenderer]
mesh = "meshes/crate.glb"
material = "materials/crate.mat"

[Prefab.Components.Collider]
shape = "box"
offset = [0.0, 0.0]
size = [225.0, 225.0]
enabled = true
is_trigger = false
friction = 0.6

[Prefab.Components.Rigidbody]
body_type = "static"
simulated = true
use_gravity = false
mass = 10.0
freeze_rotation = true

[Prefab.Components.Health]
current = 40
max = 40

[Prefab.Components.Script]
module = "scripts/crate.lua"

[Prefab.Components.StaticSprite]
texture = "assets/Sprites/crate.jpeg"
position = [0.0, 0.0]
scale = 1.0